repositoryUrl: https://github.com/dynamsoft-docs/capture-vision-docs-mobile/blob/main
repository: dynamsoft-docs/capture-vision-docs-mobile
docFullPath: https://www.dynamsoft.com/capture-vision/docs/mobile/
firstLevelUrl: /capture-vision/docs/mobile
docHomePage: /capture-vision/docs/core/introduction/
frontPageFolder: /capture-vision/docs/
searchIndexName: Crawler-DCV-Docs-New
searchNeedFilter: true

productName: Dynamsoft Capture Vision

programming: /capture-vision/docs/mobile/programming/

architecture: /capture-vision/docs/core/architecture/
parameter: /capture-vision/docs/core/parameters/

license: /capture-vision/docs/mobile/license/

dcv_license_activation: /capture-vision/docs/core/license/

faq: /capture-vision/docs/mobile/faq/

introduction: /capture-vision/docs/mobile/introduction/
performance: /barcode-reader/docs/core/performance/

react-native: /capture-vision/docs/mobile/programming/react-native/
rn-api: /capture-vision/docs/mobile/programming/react-native/api-reference/
rn-release-notes: /capture-vision/docs/mobile/programming/react-native/release-notes/
rn-guide: /capture-vision/docs/mobile/programming/react-native/user-guide/

cordova: /capture-vision/docs/mobile/programming/cordova/
cordova-api: /capture-vision/docs/mobile/programming/cordova/api-reference/
cordova-release-notes: /capture-vision/docs/mobile/programming/cordova/release-notes/
cordova-guide: /capture-vision/docs/mobile/programming/cordova/user-guide/

dcv_flutter: /capture-vision/docs/mobile/programming/flutter/
dcv_flutter_api: /capture-vision/docs/mobile/programming/flutter/api-reference/
dbr_flutter: /barcode-reader/docs/mobile/programming/flutter/
dbr_flutter_api: /barcode-reader/docs/mobile/programming/flutter/api-reference/
dcp_flutter: /code-parser/docs/mobile/programming/flutter/
dcp_flutter_api: /code-parser/docs/mobile/programming/flutter/api-reference/
dce_flutter: /camera-enhancer/docs/mobile/programming/flutter/
dce_flutter_api: /camera-enhancer/docs/mobile/programming/flutter/api-reference/
ddn_flutter: /document-normalizer/docs/mobile/programming/flutter/
ddn_flutter_api: /document-normalizer/docs/mobile/programming/flutter/api-reference/ 
dlr_flutter: /label-recognition/docs/mobile/programming/flutter/
dlr_flutter_api: /label-recognition/docs/mobile/programming/flutter/api-reference/

dcv_react_native: /capture-vision/docs/mobile/programming/react-native/
dcv_react_native_api: /capture-vision/docs/mobile/programming/react-native/api-reference/
dce_react_native: /camera-enhancer/docs/mobile/programming/react-native/
dce_react_native_api: /camera-enhancer/docs/mobile/programming/react-native/api-reference/
dcp_react_native: /code-parser/docs/mobile/programming/react-native/
dcp_react_native_api: /code-parser/docs/mobile/programming/react-native/api-reference/
dbr_react_native: /barcode-reader/docs/mobile/programming/react-native/
dbr_react_native_api: /barcode-reader/docs/mobile/programming/react-native/api-reference/
ddn_react_native: /document-normalizer/docs/mobile/programming/react-native/
ddn_react_native_api: /document-normalizer/docs/mobile/programming/react-native/api-reference/ 
dlr_react_native: /label-recognition/docs/mobile/programming/react-native/
dlr_react_native_api: /label-recognition/docs/mobile/programming/react-native/api-reference/

xamarin: /capture-vision/docs/mobile/programming/xamarin/
xamarin-api: /capture-vision/docs/mobile/programming/xamarin/api-reference/
xamarin-release-notes: /capture-vision/docs/mobile/programming/xamarin/release-notes/
xamarin-guide: /capture-vision/docs/mobile/programming/xamarin/user-guide/

dcv_android: /capture-vision/docs/mobile/programming/android/
dcv_android_api: /capture-vision/docs/mobile/programming/android/api-reference/
dcv_android_v2: /capture-vision/docs/v2/mobile/programming/android/

dcv_ios: /capture-vision/docs/mobile/programming/ios/
dcv_ios_api: /capture-vision/docs/mobile/programming/ios/api-reference/
dcv_ios_v2: /capture-vision/docs/v2/mobile/programming/ios/

ddn_android_api: /document-normalizer/docs/mobile/programming/android/api-reference/
ddn_android: /document-normalizer/docs/mobile/programming/android/
ddn_ios_api: /document-normalizer/docs/mobile/programming/ios/api-reference/
ddn_ios: /document-normalizer/docs/mobile/programming/ios/
ddn_maui_api: /document-normalizer/docs/mobile/programming/maui/api-reference/
ddn_maui: /document-normalizer/docs/mobile/programming/maui/
dce_android_api: /camera-enhancer/docs/mobile/programming/android/
dce_ios_api: /camera-enhancer/docs/mobile/programming/ios/

dbr_android: /barcode-reader/docs/mobile/programming/android/
dbr_android_api: /barcode-reader/docs/mobile/programming/android/api-reference/
dbr_ios: /barcode-reader/docs/mobile/programming/objectivec-swift/
dbr_ios_api: /barcode-reader/docs/mobile/programming/objectivec-swift/api-reference/

dbr_features: /barcode-reader/docs/core/programming/features/

dlr_android: /label-recognition/docs/mobile/programming/android/
dlr_android_api: /label-recognition/docs/mobile/programming/android/api-reference/
dlr_ios: /label-recognition/docs/mobile/programming/objectivec-swift/
dlr_ios_api: /label-recognition/docs/mobile/programming/objectivec-swift/api-reference/
dcp_android: /code-parser/docs/mobile/programming/android/
dcp_android_api: /code-parser/docs/mobile/programming/android/api-reference/
dcp_ios: /code-parser/docs/mobile/programming/ios/
dcp_ios_api: /code-parser/docs/mobile/programming/ios/api-reference/

dce_enumerations: /camera-enhancer/docs/core/enums/
dcv_enumerations: /capture-vision/docs/core/enums/
architecture: /capture-vision/docs/core/architecture/
dcv_parameters_reference: /capture-vision/docs/core/parameters/reference/
dcvb_introduction: /capture-vision/docs/core/introduction/
dcvb_root: /capture-vision/docs/core/


dbr_maui: /barcode-reader/docs/mobile/programming/maui/
dbr_maui_api: /barcode-reader/docs/mobile/programming/maui/api-reference/
dlr_maui: /label-recognition/docs/mobile/programming/maui/
dlr_maui_api: /label-recognition/docs/mobile/programming/maui/api-reference/
ddn_maui: /document-normalizer/docs/mobile/programming/maui/
ddn_maui_api: /document-normalizer/docs/mobile/programming/maui/api-reference/
dcv_maui: /capture-vision/docs/mobile/programming/maui/
dcv_maui_api: /capture-vision/docs/mobile/programming/maui/api-reference/
dcv_maui_v2: /capture-vision/docs/v2/mobile/programming/maui/
dce_maui: /camera-enhancer/docs/mobile/programming/maui/
dce_maui_api: /camera-enhancer/docs/mobile/programming/maui/api-reference/
dcp_maui: /code-parser/docs/mobile/programming/maui/
dcp_maui_api: /code-parser/docs/mobile/programming/maui/api-reference/

dcv_cpp: /capture-vision/docs/server/programming/cplusplus/
dcv_python: /capture-vision/docs/server/programming/python/
dcv_java: /capture-vision/docs/server/programming/java/
dcv_dotnet: /capture-vision/docs/server/programming/dotnet/
dcv_js: /capture-vision/docs/web/programming/javascript/

code_types: /code-parser/docs/core/code-types/

assets: /capture-vision/docs/mobile/assets/
edit_icon: /capture-vision/docs/mobile/assets/img-icon/edit-icon.png
smile_icon: /capture-vision/docs/mobile/assets/img-icon/icon-smile.png
sad_icon: /capture-vision/docs/mobile/assets/img-icon/icon-sad.png
dbr_icon: /capture-vision/docs/mobile/assets/img-icon/icon-dbr.svg
dwt_icon: /capture-vision/docs/mobile/assets/img-icon/icon-dwt.svg
dnt_icon: /capture-vision/docs/mobile/assets/img-icon/icon-dnt.svg

download: /capture-vision/downloads/1000024-confirmation/

useVersionTree: true
useJSVersionV3: true

baseurl: "/capture-vision/docs/mobile/"
plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-webp
  - jekyll-relative-links
  - jekyll-redirect-from
  - jekyll-readme-index
  - jekyll-seo-tag

edition: mobile

defaults:
  - scope:
      path: "Hide_Tree_Page.html"
    values:
      sitemap: false
  - scope:
      path: "programming/android"
    values:
      docRootName: "Capture Vision Android Edition" 
      docHomePage: "/capture-vision/docs/mobile/programming/android/"
  - scope:
      path: "programming/ios"
    values:
      docRootName: "Capture Vision iOS Edition" 
      docHomePage: "/capture-vision/docs/mobile/programming/ios/"
  - scope:
      path: "programming/maui"
    values:
      docRootName: "Capture Vision MAUI Edition" 
      docHomePage: "/capture-vision/docs/mobile/programming/maui/"
  - scope:
      path: "programming/flutter"
    values:
      docRootName: "Capture Vision Flutter Edition" 
      docHomePage: "/capture-vision/docs/mobile/programming/flutter/"      
  - scope:
      path: "programming/react-native"
    values:
      docRootName: "Capture Vision React-Native Edition" 
      docHomePage: "/capture-vision/docs/mobile/programming/react-native/" 
  - scope:
      path: "programming/xamarin"
    values:
      docRootName: "Capture Vision Xamarin Edition" 
      docHomePage: "/capture-vision/docs/mobile/programming/xamarin/" 
  - scope:
      path: "programming/cordova"
    values:
      docRootName: "Capture Vision Cordova Edition" 
      docHomePage: "/capture-vision/docs/mobile/programming/cordova/"

url: "https://www.dynamsoft.com" # sitemap root
