repositoryUrl: https://github.com/dynamsoft-docs/capture-vision-docs-mobile
repository: dynamsoft-docs/capture-vision-docs-mobile
docFullPath: https://www.dynamsoft.com/capture-vision/docs
firstLevelUrl: /capture-vision/docs
docHomePage: /capture-vision/docs/
frontPageFolder: /capture-vision/docs/

productName: Dynamsoft Capture Vision

programming: /capture-vision/docs/programming/

license: /capture-vision/docs/license/

introduction: /capture-vision/docs/introduction/

react-native: /capture-vision/docs/programming/react-native/
rn-api: /capture-vision/docs/programming/react-native/api-reference/
rn-release-notes: /capture-vision/docs/programming/react-native/release-notes/
rn-guide: /capture-vision/docs/programming/react-native/user-guide/

flutter: /capture-vision/docs/programming/flutter/
flutter-api: /capture-vision/docs/programming/flutter/api-reference/
flutter-release-notes: /capture-vision/docs/programming/flutter/release-notes/
flutter-guide: /capture-vision/docs/programming/flutter/user-guide/

assets: /capture-vision/docs/assets/
edit_icon: /capture-vision/docs/assets/img-icon/edit-icon.png
smile_icon: /capture-vision/docs/assets/img-icon/icon-smile.png
sad_icon: /capture-vision/docs/assets/img-icon/icon-sad.png
dbr_icon: /capture-vision/docs/assets/img-icon/icon-dbr.svg
dwt_icon: /capture-vision/docs/assets/img-icon/icon-dwt.svg
dnt_icon: /capture-vision/docs/assets/img-icon/icon-dnt.svg

download: /capture-vision/downloads/1000021-confirmation/

useVersionTree: true

baseurl: "/capture-vision/docs/"
plugins:
  - jemoji
  - jekyll-sitemap
  
defaults:
  - scope:
      path: "Hide_Tree_Page.html"
    values:
      sitemap: false

url: "https://www.dynamsoft.com" # sitemap root
