# This is a basic workflow to help you get started with Actions

name: Full-Site-Build

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build-Main:
    if: ${{ github.ref == 'refs/heads/main' }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Build the site
        run: |
          cd /home/ubuntu
          [ -d DCVDoc ] && rm -rf DCVDoc
          [ ! -d DCVDoc ] && mkdir -p DCVDoc
          cd capture-vision-docs-mobile && git pull && cd .. && cp -rfp ./capture-vision-docs-mobile/* ./DCVDoc/
          cd Docs-Template-Repo-preview && git pull && cd .. && cp -rfp ./Docs-Template-Repo-preview/* ./DCVDoc/
          cd DCVDoc && bundle exec jekyll build
          python3 /home/ubuntu/ftp.py /home/ubuntu/DCVDoc/_site/ ./www.dynamsoft.com/capture-vision/docs/ prod
         
  Build-Preview:
    if: ${{ github.ref == 'refs/heads/preview' }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Build the site
        run: |
          cd /home/ubuntu
          [ -d DCVDocPreview ] && rm -rf DCVDocPreview
          [ -d capture-vision-docs-mobile-preview ] && rm -rf capture-vision-docs-mobile-preview
          [ ! -d DCVDocPreview ] && mkdir -p DCVDocPreview
          [ ! -d capture-vision-docs-mobile-preview ] && git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/capture-vision-docs-mobile.git capture-vision-docs-mobile-preview
          cd capture-vision-docs-mobile-preview && git pull && cd .. && cp -rfp ./capture-vision-docs-mobile-preview/* ./DCVDocPreview/
          cd Docs-Template-Repo-preview && git pull && cd .. && cp -rfp ./Docs-Template-Repo-preview/* ./DCVDocPreview/
          sed -i -e "1,3s/blob\/master$/blob\/preview/" \
          -e "1,3s/blob\/main$/blob\/preview/" /home/ubuntu/DCVDocPreview/_config.yml
          cd DCVDocPreview && bundle exec jekyll build

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_TEST_SITE_SERVER }}
          username: ${{ secrets.FTP_TEST_SITE_USER }}
          password: ${{ secrets.FTP_TEST_SITE_PASSWORD }}
          port: 7500 
          local-dir: /home/ubuntu/DCVDocPreview/_site/
          server-dir: /www.dynamsoft.com/capture-vision/docs/          
